import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";
import { Link } from "lucide-react";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus = [
    { texto: "Inicio", link: "/" },
    { texto: "Ofertas", link: "/ofertas" },
    { texto: "Habitaciones", link: "/habitaciones" },
    { texto: "Reservaciones", link: "/reservaciones" },
    { texto: "Contacto", link: "/contacto" },
  ];

  return (
    <html lang='en'>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className=''>{children}</main>
      </body>
    </html>
  );
}
