import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import { Inter as FontSans } from 'next/font/google';
import Footer from '@/components/footer/footer';
import Navbar from '@/app/(site)/navbar/navigation';
import Provider from '@/app/(site)/navbar/usersComponents/Provider';
import { Toaster } from '@/components/ui/toaster';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata: Metadata = {
  title: 'Sirmh.com | Sitio oficial',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      <main className="">{children}</main>
      <Footer />
      <Toaster />
    </div>
  );
}
